import './styles/main.scss';
import welcome from './styles/assets/welcome.mp4';
import "./styles/assets/background.png";
import "./styles/assets/mongoDB_logo.png";
import "./styles/assets/neo4j_logo.png";
import "./styles/assets/redux-logo.png";
import "./styles/assets/ts-logo.png";
import "./styles/assets/nodejs_logo.png";
import "./styles/assets/js_logo.png";
import "./styles/assets/html5_logo.png";
import "./styles/assets/css3_logo.png";
import "./styles/assets/react_logo.png";
import "./styles/assets/sass_logo.png";
import "./styles/assets/jira_logo.png";
import "./styles/assets/trello_logo.png";
import "./styles/assets/go_logo.png";
import "./styles/assets/budget.jpg";
import "./styles/assets/drinks.jpg";
import "./styles/assets/gallery.jpeg";
import "./styles/assets/lifechat.jpg";
import "./styles/assets/manage_app.jpg";
import "./styles/assets/owl.png";
import "./styles/assets/safety-list.jpg";
import "./styles/assets/weather.jpeg";
import "./styles/assets/landing.png";
import "./styles/assets/gms.jpg";
import "./styles/assets/WAS-CSS.png";
import "./styles/assets/favicon.svg";


import './js/welcome';
import './js/road';
